2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_setup.py:_flush():69] setting env: {}
2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_init.py:_log_setup():336] Logging user logs to ../logs/p1/wandb/run-20210423_151231-baseline_0_0/logs/debug.log
2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_init.py:_log_setup():337] Logging internal logs to ../logs/p1/wandb/run-20210423_151231-baseline_0_0/logs/debug-internal.log
2021-04-23 15:12:31,413 INFO    MainThread:776333 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f205983bdc0>
2021-04-23 15:12:31,414 INFO    MainThread:776333 [wandb_init.py:init():369] calling init triggers
2021-04-23 15:12:31,414 INFO    MainThread:776333 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-23 15:12:31,414 INFO    MainThread:776333 [wandb_init.py:init():418] starting backend
2021-04-23 15:12:31,414 INFO    MainThread:776333 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-23 15:12:31,444 INFO    MainThread:776333 [backend.py:ensure_launched():123] starting backend process...
2021-04-23 15:12:31,471 INFO    MainThread:776333 [backend.py:ensure_launched():127] started backend process with pid: 776407
2021-04-23 15:12:31,472 INFO    MainThread:776333 [wandb_init.py:init():423] backend started and connected
2021-04-23 15:12:31,492 INFO    MainThread:776333 [wandb_init.py:init():465] updated telemetry
2021-04-23 15:12:31,509 INFO    MainThread:776333 [wandb_init.py:init():484] communicating current version
2021-04-23 15:12:32,109 INFO    MainThread:776333 [wandb_init.py:init():489] got version response 
2021-04-23 15:12:32,109 INFO    MainThread:776333 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-23 15:12:52,689 WARNING MainThread:776333 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 498, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 652, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 640, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/python/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/python/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
